(defun my-spec (lc-dir-x lc-dir-y lc-dir-z nx ny nz dx dy dz)
  (let* ((dot-l-n (+ (* (- lc-dir-x) nx) (* (- lc-dir-y) ny) (* (- lc-dir-z) nz)))
         (rx-l (- (- lc-dir-x) (* 2.0 dot-l-n nx)))
         (ry-l (- (- lc-dir-y) (* 2.0 dot-l-n ny)))
         (rz-l (- (- lc-dir-z) (* 2.0 dot-l-n nz)))
         (dot-r-v (+ (* rx-l (- dx)) (* ry-l (- dy)) (* rz-l (- dz))))
         (vdot (max 0.0 dot-r-v)))
    (format t "FIXED: dot-l-n=~A, rx=~A, ry=~A, rz=~A, dot-r-v=~A, vdot=~A~%" dot-l-n rx-l ry-l rz-l dot-r-v vdot)))

(defun old-spec (lc-dir-x lc-dir-y lc-dir-z nx ny nz dx dy dz)
  (let* ((dot-l-n (+ (* lc-dir-x nx) (* lc-dir-y ny) (* lc-dir-z nz)))
         (rx-l (- lc-dir-x (* 2.0 dot-l-n nx)))
         (ry-l (- lc-dir-y (* 2.0 dot-l-n ny)))
         (rz-l (- lc-dir-z (* 2.0 dot-l-n nz)))
         (dot-r-v (+ (* rx-l (- dx)) (* ry-l (- dy)) (* rz-l (- dz))))
         (vdot (max 0.0 dot-r-v)))
    (format t "OLD:   dot-l-n=~A, rx=~A, ry=~A, rz=~A, dot-r-v=~A, vdot=~A~%" dot-l-n rx-l ry-l rz-l dot-r-v vdot)))

;; Test with plane: light above, camera looking from angle
;; lc-dir (from point to light): (0.35, -0.116, 0.93)
;; Normal (plane): (0, -1, 0)
;; Camera ray (from eye to point): (-0.24, 0.38, -0.89)
(my-spec 0.35 -0.116 0.93 0.0 -1.0 0.0 -0.24 0.38 -0.89)
(old-spec 0.35 -0.116 0.93 0.0 -1.0 0.0 -0.24 0.38 -0.89)
